export enum Actions {
  PURCHASE = "PURCHASE",
  ACCEPT = "ACCEPT",
  SETTLE = "SETTLE",
  CHARGE = "CHARGE",
  REFUND = "REFUND",
  CHECK_STATUS = "CHECK_STATUS",
  P2P_CREDIT = "P2P_CREDIT",
  CREATE_INVOICE = "CREATE_INVOICE",
  P2_PHONE = "P2_PHONE",
  COMPLETE_3DS = "COMPLETE_3DS",
  VERIFY = "VERIFY",
  INITIAL = "INITIAL"
}
